# Generated by Django 3.2.4 on 2021-08-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField(default=True)),
                ('nationality', models.CharField(choices=[('k', 'KENYA'), ('g', 'UGANDA'), ('r', 'RWANDA')], max_length=12)),
                ('Student_id', models.CharField(blank=True, max_length=12)),
                ('image_of_the_student', models.ImageField(upload_to='register_student')),
                ('passport', models.CharField(max_length=10)),
                ('email', models.EmailField(default=0, max_length=254)),
                ('gender', models.CharField(choices=[('F', 'female'), ('m', 'male'), ('o', 'other')], max_length=12)),
                ('subject', models.CharField(max_length=14)),
                ('health_records', models.FileField(upload_to='')),
                ('classroom', models.CharField(default=False, max_length=10)),
                ('phone_number', models.CharField(max_length=12)),
                ('admission_date', models.DateField(default=True)),
                ('parent_contact', models.CharField(max_length=12)),
                ('academic_year', models.DateField(default=False, max_length=8)),
                ('Language', models.CharField(blank=True, choices=[('E', 'English'), ('K', 'Kiswahili'), ('F', 'French')], max_length=15)),
            ],
        ),
    ]
