# Generated by Django 3.2.4 on 2021-08-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210817_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('kenya', 'KENYA'), ('uganda', 'UGANDA'), ('Rwanda', 'RWANDA')], max_length=12),
        ),
    ]
