# Generated by Django 3.2.4 on 2021-08-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_nationality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Language',
            new_name='language',
        ),
    ]
