# Generated by Django 3.2.4 on 2021-08-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_language_student_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Kiswahili', 'Kiswahili'), ('French', 'French')], max_length=15),
        ),
    ]
